## Insertion Sort

In [1]:
import numpy as np 
from datetime import datetime

In [18]:
check = np.random.randint(100, size=10)
check

array([44, 64, 15, 74, 65,  6, 28, 68, 67, 94])

In [22]:
check2 = np.random.randint(100, size=10)
check2

array([ 3, 14, 66, 15, 73, 73, 13, 64, 17, 48])

In [13]:
def InsertionSort(list):
    for i in range(1, len(list)): 
        key = list[i] 
        j = i-1
        while j >= 0 and key < list[j] : 
                list[j + 1] = list[j] 
                j -= 1
        list[j + 1] = key 

In [19]:
start_time = datetime.now()
InsertionSort(check)
time_elapsed = datetime.now() - start_time
print(check, "\n", time_elapsed)

[ 6 15 28 44 64 65 67 68 74 94] 
 0:00:00.000209


In [23]:
start_time2 = datetime.now()
InsertionSort(check2)
time_elapsed2 = datetime.now() - start_time2
print(check2, "\n", time_elapsed2)

[ 3 13 14 15 17 48 64 66 73 73] 
 0:00:00.000149
